### ISSUE TITLE
Interpretation of coordination in A5SS

### ISSUE THREAD

**Issue by kwonej0617** [Xinglab/rMATS-long#23]
Hi @EricKutschera 

I have a question regarding interpretation of A5SS coordination.
Could you please explain what those coordinations represent? Why does A5SS event have two coordination connecting with ";"? 
In addition, even though transcript 1 and 2 are the same in both 1) and 2), why are the coordination different?

transcript1     transcript2     event   coordinates
1) ENST00000355299.8       ENST00000559910.5       A5SS    **chr14:24232422:24232788:+;chr14:24232422:24232847:+**
2) ENST00000355299.8       ENST00000559910.5       A5SS    **chr14:24235967:24236041:+;chr14:24235967:24236140:+**

![image](https://github.com/user-attachments/assets/9f6c7ff0-93ac-4149-90c2-89f4ff86f19e)

Looking forward to hearing from you.
Thank you.

**Comment by EricKutschera** [comment]
The two coordinates separated by `;` are the coordinates of the exon with the different splice site in the two transcripts. Here are the exon coordinates for the two transcripts being compared
ENST00000355299.8: https://useast.ensembl.org/Homo_sapiens/Transcript/Exons?db=core;g=ENSG00000100938;r=14:24232422-24239242;t=ENST00000355299
```
24,232,422 24,232,847
24,233,219 24,233,340
24,233,479 24,233,598
24,235,737 24,235,820
24,235,967 24,236,140
24,237,071 24,237,152
24,237,245 24,237,351
24,237,520 24,237,562
24,238,246 24,238,405
24,238,589 24,239,242
```
ENST00000559910.5: https://useast.ensembl.org/Homo_sapiens/Transcript/Exons?db=core;g=ENSG00000100938;r=14:24232422-24239242;t=ENST00000559910
```
24,232,636 24,232,788
24,233,219 24,233,340
24,233,479 24,233,598
24,235,737 24,235,820
24,235,967 24,236,041
24,237,071 24,237,152
24,237,245 24,237,351
24,237,520 24,237,562
24,238,246 24,238,405
24,238,589 24,239,204
```
The differences are exons 1, 5, and 10:
24,232,422 24,232,847
24,232,636 24,232,788

24,235,967 24,236,140
24,235,967 24,236,041

24,238,589 24,239,242
24,238,589 24,239,204

rMATS-long doesn't compare the transcript start and end coordinates: https://github.com/Xinglab/rMATS-long/blob/v1.0.0/scripts/FindAltTSEvents.py#L173 so in your example it used 24,232,422 as the start coordinate for both transcripts when reporting the first A5SS event

**Comment by kwonej0617** [comment]
Thank you @EricKutschera!
