### ISSUE TITLE
differential genes/transcripts files

### ISSUE THREAD

**Issue by trista1115** [Xinglab/rMATS-long#25]
Hi @EricKutschera 

When I ran ESPRESSO, the abundance file reported around 13,000 genes, but rmats-long produced a `differential_genes.tsv` file with only 9,800 genes. I'm a bit confused about how the `differential_genes.tsv` file and `differential_transcripts.tsv` was generated. Could you clarify the process?

Thanks.

**Comment by trista1115** [comment]
Hi @EricKutschera 

How are the red and blue colors assigned to isoforms in the structure and abundance plots? What is the logic behind the color assignment in these plots?

1.Some structure plots lack colors, while the abundance plot includes them.
> 
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/8fd74b59-4195-4009-80d5-df434f6980b7">

2. What do the red and blue colors represent in the abundance plot? In some plots, red isoform domains are associated with group A, while in others they are associated with group B.

> 
<img width="483" alt="image" src="https://github.com/user-attachments/assets/9cfe1da3-9c90-41f5-a809-ba1dc289cec6">
<img width="522" alt="image" src="https://github.com/user-attachments/assets/baf5b258-a2ae-4451-8e10-e137922998d0">

**Comment by EricKutschera** [comment]
The red isoform is the most significant. The blue isoform is the next most significant isoform with delta proportion in the opposite direction. All the other isoforms will be grey. The isoforms will have the same color in the abunance and structure plot for the same gene

If the isoform diff file is empty then the isoforms differ only by endpoints. ESPRESSO won't detect a novel isoform that only differs by an endpoint, but ESPRESSO will distinguish two annotated trancripts that differ by endpoints: https://github.com/Xinglab/rMATS-long/issues/22#issuecomment-2221235290
